In [1]:
import os
import shutil
import subprocess

import anndata as ad
import numpy as np
import pandas as pd
import scanpy as sc
from scipy.sparse import csr_matrix

In [2]:
# Clone repo at https://github.com/LieberInstitute/HumanPilot and set DIR to it
DIR = "../HumanPilot"
OUT_DIR = "data/dlpfc/raw/spatialLIBD"
R_DIR = "data/dlpfc/spatialLIBD_data"

In [ ]:
aws_sources_df = pd.read_csv(os.path.join(DIR, "AWS_File_locations.tsv"), sep="\t", index_col=0)
aws_sources_df

,h5_filtered,h5_raw,image_full,image_hi,image_lo,loupe
SampleID,,,,,,
151507,https://spatial-dlpfc.s3.us-east-2.amazonaws.c...,https://spatial-dlpfc.s3.us-east-2.amazonaws.c...,https://spatial-dlpfc.s3.us-east-2.amazonaws.c...,https://spatial-dlpfc.s3.us-east-2.amazonaws.c...,https://spatial-dlpfc.s3.us-east-2.amazonaws.c...,https://spatial-dlpfc.s3.us-east-2.amazonaws.c...
151508,https://spatial-dlpfc.s3.us-east-2.amazonaws.c...,https://spatial-dlpfc.s3.us-east-2.amazonaws.c...,https://spatial-dlpfc.s3.us-east-2.amazonaws.c...,https://spatial-dlpfc.s3.us-east-2.amazonaws.c...,https://spatial-dlpfc.s3.us-east-2.amazonaws.c...,https://spatial-dlpfc.s3.us-east-2.amazonaws.c...
151509,https://spatial-dlpfc.s3.us-east-2.amazonaws.c...,https://spatial-dlpfc.s3.us-east-2.amazonaws.c...,https://spatial-dlpfc.s3.us-east-2.amazonaws.c...,https://spatial-dlpfc.s3.us-east-2.amazonaws.c...,https://spatial-dlpfc.s3.us-east-2.amazonaws.c...,https://spatial-dlpfc.s3.us-east-2.amazonaws.c...
151510,https://spatial-dlpfc.s3.us-east-2.amazonaws.c...,https://spatial-dlpfc.s3.us-east-2.amazonaws.c...,https://spatial-dlpfc.s3.us-east-2.amazonaws.c...,https://spatial-dlpfc.s3.us-east-2.amazonaws.c...,https://spatial-dlpfc.s3.us-east-2.amazonaws.c...,https://spatial-dlpfc.s3.us-east-2.amazonaws.c...
151669,https://spatial-dlpfc.s3.us-east-2.amazonaws.c...,https://spatial-dlpfc.s3.us-east-2.amazonaws.c...,https://spatial-dlpfc.s3.us-east-2.amazonaws.c...,https://spatial-dlpfc.s3.us-east-2.amazonaws.c...,https://spatial-dlpfc.s3.us-east-2.amazonaws.c...,https://spatial-dlpfc.s3.us-east-2.amazonaws.c...
151670,https://spatial-dlpfc.s3.us-east-2.amazonaws.c...,https://spatial-dlpfc.s3.us-east-2.amazonaws.c...,https://spatial-dlpfc.s3.us-east-2.amazonaws.c...,https://spatial-dlpfc.s3.us-east-2.amazonaws.c...,https://spatial-dlpfc.s3.us-east-2.amazonaws.c...,https://spatial-dlpfc.s3.us-east-2.amazonaws.c...
151671,https://spatial-dlpfc.s3.us-east-2.amazonaws.c...,https://spatial-dlpfc.s3.us-east-2.amazonaws.c...,https://spatial-dlpfc.s3.us-east-2.amazonaws.c...,https://spatial-dlpfc.s3.us-east-2.amazonaws.c...,https://spatial-dlpfc.s3.us-east-2.amazonaws.c...,https://spatial-dlpfc.s3.us-east-2.amazonaws.c...
151672,https://spatial-dlpfc.s3.us-east-2.amazonaws.c...,https://spatial-dlpfc.s3.us-east-2.amazonaws.c...,https://spatial-dlpfc.s3.us-east-2.amazonaws.c...,https://spatial-dlpfc.s3.us-east-2.amazonaws.c...,https://spatial-dlpfc.s3.us-east-2.amazonaws.c...,https://spatial-dlpfc.s3.us-east-2.amazonaws.c...
151673,https://spatial-dlpfc.s3.us-east-2.amazonaws.c...,https://spatial-dlpfc.s3.us-east-2.amazonaws.c...,https://spatial-dlpfc.s3.us-east-2.amazonaws.c...,https://spatial-dlpfc.s3.us-east-2.amazonaws.c...,https://spatial-dlpfc.s3.us-east-2.amazonaws.c...,https://spatial-dlpfc.s3.us-east-2.amazonaws.c...
151674,https://spatial-dlpfc.s3.us-east-2.amazonaws.c...,https://spatial-dlpfc.s3.us-east-2.amazonaws.c...,https://spatial-dlpfc.s3.us-east-2.amazonaws.c...,https://spatial-dlpfc.s3.us-east-2.amazonaws.c...,https://spatial-dlpfc.s3.us-east-2.amazonaws.c...,https://spatial-dlpfc.s3.us-east-2.amazonaws.c...
151675,https://spatial-dlpfc.s3.us-east-2.amazonaws.c...,https://spatial-dlpfc.s3.us-east-2.amazonaws.c...,https://spatial-dlpfc.s3.us-east-2.amazonaws.c...,https://spatial-dlpfc.s3.us-east-2.amazonaws.c...,https://spatial-dlpfc.s3.us-east-2.amazonaws.c...,https://spatial-dlpfc.s3.us-east-2.amazonaws.c...
151676,https://spatial-dlpfc.s3.us-east-2.amazonaws.c...,https://spatial-dlpfc.s3.us-east-2.amazonaws.c...,https://spatial-dlpfc.s3.us-east-2.amazonaws.c...,https://spatial-dlpfc.s3.us-east-2.amazonaws.c...,https://spatial-dlpfc.s3.us-east-2.amazonaws.c...,https://spatial-dlpfc.s3.us-east-2.amazonaws.c...

In [4]:
# if not os.path.exists(OUT_DIR):
#     os.makedirs(OUT_DIR)


for sample_id in aws_sources_df.index:

    sdir = os.path.join(OUT_DIR, str(sample_id))
    sdir_sp = os.path.join(sdir, "spatial")

    if not os.path.exists(sdir_sp):
        os.makedirs(sdir_sp)

    shutil.copytree(
        os.path.join(DIR, "10X", str(sample_id)),
        os.path.join(sdir_sp),
        dirs_exist_ok=True,
    )

    os.rename(
        os.path.join(sdir_sp, "tissue_positions_list.txt"),
        os.path.join(sdir_sp, "tissue_positions_list.csv"),
    )

    subprocess.run(
        [
            "curl",
            "-L",
            "-o",
            "filtered_feature_bc_matrix.h5",
            aws_sources_df.loc[sample_id, "h5_filtered"],
        ],
        cwd=sdir,
    )

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 9999k  100 9999k    0     0  9415k      0  0:00:01  0:00:01 --:--:-- 9415k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 9036k  100 9036k    0     0  9748k      0 --:--:-- --:--:-- --:--:-- 9737k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 10.9M  100 10.9M    0     0  5071k      0  0:00:02  0:00:02 --:--:-- 5071k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 10.2M  100 10.2M    0     0  5750k      0  0:00:01  0:00:01 --:--:-- 5747k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 10.5M  100 10.5M    0     0  6033k      0  0:00:01  0:00:01 --:--:-- 6030k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 9808k  100 9808k    0     0  11.8M      0 --:--:-- --:--:-- --:--:-- 11.8M
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 11.8M  100 11.8M    0     0  12.2M      0 --:--:-- --:--:-- --:--:-- 12.1M
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 11.1M  100 11.1M    0     0  10.7M      0  0:00:01  0:00:01 --:--:-- 10.7M
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 12.2M  100 12.2M    0     0  6918k      0  0:00:01  0:00:01 --:--:-- 6914k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 14.7M  100 14.7M    0     0  4664k      0  0:00:03  0:00:03 --:--:-- 4665k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 10.3M  100 10.3M    0     0  5297k      0  0:00:02  0:00:02 --:--:-- 5297k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 10.6M  100 10.6M    0     0  6164k      0  0:00:01  0:00:01 --:--:-- 6164k

In [5]:
adatas = []

for sample_id in aws_sources_df.index:

    sdir = os.path.join(OUT_DIR, str(sample_id))
    adatas.append(sc.read_visium(sdir))
    adatas[-1].var_names.name = "gene_names"
    adatas[-1].var = adatas[-1].var.reset_index().set_index("gene_ids")

adata = ad.concat(
    adatas,
    keys=aws_sources_df.index.astype(str),
    label="sample_id",
    index_unique=".",
    uns_merge="unique",
)

all_var = [x.var for x in adatas]
# concatenate them
all_var = pd.concat(all_var, join="outer")
# remove duplicates
all_var = all_var[~all_var.index.duplicated()]

adata.var = all_var.loc[adata.var_names]

/home/wma/AGrEDA/.venv/lib/python3.8/site-packages/anndata/_core/anndata.py:1830: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/home/wma/AGrEDA/.venv/lib/python3.8/site-packages/anndata/_core/anndata.py:1830: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/home/wma/AGrEDA/.venv/lib/python3.8/site-packages/anndata/_core/anndata.py:1830: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/home/wma/AGrEDA/.venv/lib/python3.8/site-packages/anndata/_core/anndata.py:1830: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/home/wma/AGrEDA/.venv/lib/python3.8/site-packages/anndata/_core/anndata.py:1830: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/home/wma/AGrEDA/.venv/lib/python3.8/site-packages/anndata/_core/anndata.py:1830: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/home/wma/AGrEDA/.venv/lib/python3.8/site-packages/anndata/_core/anndata.py:1830: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/home/wma/AGrEDA/.venv/lib/python3.8/site-packages/anndata/_core/anndata.py:1830: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/home/wma/AGrEDA/.venv/lib/python3.8/site-packages/anndata/_core/anndata.py:1830: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/home/wma/AGrEDA/.venv/lib/python3.8/site-packages/anndata/_core/anndata.py:1830: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/home/wma/AGrEDA/.venv/lib/python3.8/site-packages/anndata/_core/anndata.py:1830: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/home/wma/AGrEDA/.venv/lib/python3.8/site-packages/anndata/_core/anndata.py:1830: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")

In [6]:
# for sample_id, adata_sample in zip(aws_sources_df.index, adatas):
#     adata_sample.X = csr_matrix(adata_sample.X)
#     adata_sample.write_h5ad(os.path.join(OUT_DIR, f"spatialLIBD_{sample_id}.h5ad"))

In [7]:

adata.X = csr_matrix(adata.X)

In [8]:
adata

AnnData object with n_obs × n_vars = 47681 × 33538
    obs: 'in_tissue', 'array_row', 'array_col', 'sample_id'
    var: 'gene_names', 'feature_types', 'genome'
    uns: 'spatial'
    obsm: 'spatial'

In [9]:

adata_r = sc.read_h5ad(os.path.join(R_DIR, "spatialLIBD.h5ad"))

In [10]:
adata_r

AnnData object with n_obs × n_vars = 47681 × 33538
    obs: 'sample_id', 'spot', 'X', 'Y', 'Cluster', 'sum_umi', 'sum_gene', 'subject', 'position', 'replicate', 'subject_position', 'discard', 'key', 'cell_count', 'SNN_k50_k4', 'SNN_k50_k5', 'SNN_k50_k6', 'SNN_k50_k7', 'SNN_k50_k8', 'SNN_k50_k9', 'SNN_k50_k10', 'SNN_k50_k11', 'SNN_k50_k12', 'SNN_k50_k13', 'SNN_k50_k14', 'SNN_k50_k15', 'SNN_k50_k16', 'SNN_k50_k17', 'SNN_k50_k18', 'SNN_k50_k19', 'SNN_k50_k20', 'SNN_k50_k21', 'SNN_k50_k22', 'SNN_k50_k23', 'SNN_k50_k24', 'SNN_k50_k25', 'SNN_k50_k26', 'SNN_k50_k27', 'SNN_k50_k28', 'GraphBased', 'Maynard', 'Martinowich', 'layer_guess', 'layer_guess_reordered', 'layer_guess_reordered_short', 'expr_chrM', 'expr_chrM_ratio', 'SpatialDE_PCA', 'SpatialDE_pool_PCA', 'HVG_PCA', 'pseudobulk_PCA', 'markers_PCA', 'SpatialDE_UMAP', 'SpatialDE_pool_UMAP', 'HVG_UMAP', 'pseudobulk_UMAP', 'markers_UMAP', 'SpatialDE_PCA_spatial', 'SpatialDE_pool_PCA_spatial', 'HVG_PCA_spatial', 'pseudobulk_PCA_spatial', 'markers_PCA_spatial', 'SpatialDE_UMAP_spatial', 'SpatialDE_pool_UMAP_spatial', 'HVG_UMAP_spatial', 'pseudobulk_UMAP_spatial', 'markers_UMAP_spatial', 'spatialLIBD', 'ManualAnnotation', 'in_tissue', 'array_row', 'array_col'
    var: 'source', 'type', 'gene_version', 'gene_name', 'gene_source', 'gene_biotype', 'gene_search', 'is_top_hvg'
    varm: 'propExprsIn.Astro', 'propExprsIn.Excit_A', 'propExprsIn.Excit_B', 'propExprsIn.Excit_C', 'propExprsIn.Excit_D', 'propExprsIn.Excit_E', 'propExprsIn.Excit_F', 'propExprsIn.Inhib_A', 'propExprsIn.Inhib_B', 'propExprsIn.Inhib_C', 'propExprsIn.Inhib_D', 'propExprsIn.Inhib_E', 'propExprsIn.Inhib_F', 'propExprsIn.Macrophage', 'propExprsIn.Micro', 'propExprsIn.Mural', 'propExprsIn.OPC', 'propExprsIn.Oligo', 'propExprsIn.Tcell', 'propNucleiExprs'

In [11]:
adata

AnnData object with n_obs × n_vars = 47681 × 33538
    obs: 'in_tissue', 'array_row', 'array_col', 'sample_id'
    var: 'gene_names', 'feature_types', 'genome'
    uns: 'spatial'
    obsm: 'spatial'

In [12]:
adata_r.obs_names.to_series().str.split(".").str[0].reset_index(drop=True).equals(adata.obs_names.to_series().str.split(".").str[0].reset_index(drop=True))

True

In [13]:
adata_r.obs.sample_id.reset_index(drop=True).equals(adata.obs.sample_id.reset_index(drop=True))

True

In [14]:
np.array_equal(adata.X.toarray(), adata_r.X.toarray())

True

In [48]:
adata.var["gene_names"].equals(adata_r.var["gene_name"].rename({"gene_name": "gene_names"}))

True

In [17]:
adata.var = pd.concat([adata.var, adata_r.var.drop("gene_name", axis=1)], axis=1)

In [18]:
adata_r.obs.index = adata.obs.index

In [19]:
adata_r.obs[adata.obs.columns].astype(int).equals(adata.obs.astype(int))

True

In [20]:
adata.obs = adata_r.obs

In [21]:
adata.varm = adata_r.varm

In [22]:
np.array_equal(adata.obsm["spatial"], adata.obs[["X", "Y"]].values)

True

## Add Sex, Age, Death from Table S1

In [23]:
SUPP_TABLES_URL = "https://static-content.springer.com/esm/art%3A10.1038%2Fs41593-020-00787-0/MediaObjects/41593_2020_787_MOESM3_ESM.xlsx"
subprocess.run(
        [
            "curl",
            "-L",
            "-O",
            SUPP_TABLES_URL,
        ],
        cwd=R_DIR,
    )

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 32.0M  100 32.0M    0     0  15.8M      0  0:00:02  0:00:02 --:--:-- 15.8M

CompletedProcess(args=['curl', '-L', '-O', 'https://static-content.springer.com/esm/art%3A10.1038%2Fs41593-020-00787-0/MediaObjects/41593_2020_787_MOESM3_ESM.xlsx'], returncode=0)

In [24]:
SUPP_PATH = os.path.join(R_DIR, os.path.basename(SUPP_TABLES_URL))
table_s1 = pd.read_excel(SUPP_PATH, sheet_name="Table S1", index_col=0)

In [25]:
table_s1

,151507,151508,151509,151510,151669,151670,151671,151672,151673,151674,151675,151676
SlideID,,,,,,,,,,,,
Estimated.Number.of.Spots,4226,4384,4789,4634,3661,3498,4110,4015,3639,3673,3592,3460
Mean.Reads.per.Spot,76928,60230,58788,58482,91679,65541,118855,69943,82628,223859,64999,92701
Median.Genes.per.Spot,1384,1159,1407,1344,1737,1607,1853,1740,2113,2610,1695,1813
Number.of.Reads,325097795,264048425,281536357,271009717,335637329,229265721,488495408,280822592,300684902,822237691,233478770,320748023
Valid.Barcodes,0.969,0.969,0.965,0.966,0.972,0.972,0.971,0.972,0.97,0.971,0.97,0.972
Sequencing.Saturation,0.953,0.952,0.94,0.941,0.94,0.926,0.955,0.927,0.921,0.961,0.921,0.938
Q30.Bases.in.Barcode,0.971,0.97,0.968,0.97,0.969,0.968,0.971,0.968,0.97,0.968,0.97,0.97
Q30.Bases.in.RNA.Read,0.952,0.951,0.95,0.951,0.952,0.946,0.951,0.952,0.951,0.951,0.955,0.951
Q30.Bases.in.Sample.Index,0.915,0.949,0.968,0.96,0.964,0.937,0.941,0.964,0.952,0.962,0.872,0.965
Q30.Bases.in.UMI,0.972,0.97,0.968,0.97,0.969,0.969,0.971,0.968,0.971,0.969,0.97,0.97
Reads.Mapped.to.Genome,0.963,0.966,0.956,0.959,0.952,0.956,0.965,0.954,0.957,0.945,0.96,0.945
Reads.Mapped.Confidently.to.Genome,0.934,0.938,0.925,0.927,0.919,0.926,0.938,0.923,0.928,0.911,0.928,0.91
Reads.Mapped.Confidently.to.Intergenic.Regions,0.064,0.075,0.068,0.074,0.081,0.08,0.075,0.077,0.064,0.069,0.069,0.073
Reads.Mapped.Confidently.to.Intronic.Regions,0.019,0.018,0.02,0.019,0.019,0.019,0.018,0.018,0.022,0.023,0.022,0.022
Reads.Mapped.Confidently.to.Exonic.Regions,0.85,0.845,0.837,0.834,0.818,0.827,0.845,0.827,0.842,0.819,0.838,0.815
Reads.Mapped.Confidently.to.Transcriptome,0.795,0.793,0.773,0.775,0.777,0.785,0.798,0.784,0.795,0.776,0.794,0.776
Reads.Mapped.Antisense.to.Gene,0.033,0.028,0.041,0.036,0.019,0.02,0.025,0.02,0.024,0.021,0.021,0.017
Fraction.Reads.in.Spots,0.959,0.973,0.972,0.951,0.946,0.954,0.968,0.958,0.933,0.935,0.921,0.93
Total.Genes.Detected,21151,20737,21279,21089,21235,21019,21631,21343,21842,22437,21344,21312
Median.UMI.Counts.per.Spot,2463,2019,2416,2319,3470,3113,3743,3482,4120,5334,3139,3419
Mean.Cells.Per.Spot,2.202082,3.309991,2.993527,3.201985,2.632614,5.594911,2.732603,2.065504,4.530915,3.970868,3.457127,3.242775
Proportion.0.Cells.Per.Spot,0.243307,0.131705,0.215539,0.100979,0.058856,0.022675,0.058392,0.120113,0.023262,0.041265,0.064498,0.085106
Proportion.1.Cell.Per.Spot,0.201137,0.139009,0.132414,0.132753,0.176293,0.067164,0.164183,0.263117,0.058433,0.113618,0.160123,0.186535
Brain.Number,Br5292,Br5292,Br5292,Br5292,Br5595,Br5595,Br5595,Br5595,Br8100,Br8100,Br8100,Br8100
Position,0 µm,0 µm,300 µm,300 µm,0 µm,0 µm,300 µm,300 µm,0 µm,0 µm,300 µm,300 µm
Replicate,1,2,1,2,1,2,1,2,1,2,1,2
Age.Death,34.56,34.56,34.56,34.56,46.52,46.52,46.52,46.52,30.291695,30.291695,30.291695,30.291695
Sex,M,M,M,M,M,M,M,M,F,F,F,F
Primary.Diagnosis,Control,Control,Control,Control,Control,Control,Control,Control,Control,Control,Control,Control

In [26]:
table_s1 = table_s1.T

In [27]:
table_s1.index.name = "sample_id"
table_s1.index = table_s1.index.astype(str).astype(adata.obs["sample_id"].dtype)
table_s1.index

CategoricalIndex(['151507', '151508', '151509', '151510', '151669', '151670',
                  '151671', '151672', '151673', '151674', '151675', '151676'],
                 categories=['151507', '151508', '151509', '151510', ..., '151673', '151674', '151675', '151676'], ordered=False, dtype='category', name='sample_id')

In [28]:
table_s1.columns = table_s1.columns.str.lower().str.replace(".", "_")

/tmp/ipykernel_5491/365946333.py:1: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  table_s1.columns = table_s1.columns.str.lower().str.replace(".", "_")

In [29]:
table_s1 = table_s1.drop(["brain_number", "position", "replicate"], axis=1, errors="ignore")

In [30]:
table_s1

SlideID,estimated_number_of_spots,mean_reads_per_spot,median_genes_per_spot,number_of_reads,valid_barcodes,sequencing_saturation,q30_bases_in_barcode,q30_bases_in_rna_read,q30_bases_in_sample_index,q30_bases_in_umi,...,reads_mapped_antisense_to_gene,fraction_reads_in_spots,total_genes_detected,median_umi_counts_per_spot,mean_cells_per_spot,proportion_0_cells_per_spot,proportion_1_cell_per_spot,age_death,sex,primary_diagnosis
sample_id,,,,,,,,,,,,,,,,,,,,,
151507,4226,76928,1384,325097795,0.969,0.953,0.971,0.952,0.915,0.972,...,0.033,0.959,21151,2463,2.202082,0.243307,0.201137,34.56,M,Control
151508,4384,60230,1159,264048425,0.969,0.952,0.97,0.951,0.949,0.97,...,0.028,0.973,20737,2019,3.309991,0.131705,0.139009,34.56,M,Control
151509,4789,58788,1407,281536357,0.965,0.94,0.968,0.95,0.968,0.968,...,0.041,0.972,21279,2416,2.993527,0.215539,0.132414,34.56,M,Control
151510,4634,58482,1344,271009717,0.966,0.941,0.97,0.951,0.96,0.97,...,0.036,0.951,21089,2319,3.201985,0.100979,0.132753,34.56,M,Control
151669,3661,91679,1737,335637329,0.972,0.94,0.969,0.952,0.964,0.969,...,0.019,0.946,21235,3470,2.632614,0.058856,0.176293,46.52,M,Control
151670,3498,65541,1607,229265721,0.972,0.926,0.968,0.946,0.937,0.969,...,0.02,0.954,21019,3113,5.594911,0.022675,0.067164,46.52,M,Control
151671,4110,118855,1853,488495408,0.971,0.955,0.971,0.951,0.941,0.971,...,0.025,0.968,21631,3743,2.732603,0.058392,0.164183,46.52,M,Control
151672,4015,69943,1740,280822592,0.972,0.927,0.968,0.952,0.964,0.968,...,0.02,0.958,21343,3482,2.065504,0.120113,0.263117,46.52,M,Control
151673,3639,82628,2113,300684902,0.97,0.921,0.97,0.951,0.952,0.971,...,0.024,0.933,21842,4120,4.530915,0.023262,0.058433,30.291695,F,Control
151674,3673,223859,2610,822237691,0.971,0.961,0.968,0.951,0.962,0.969,...,0.021,0.935,22437,5334,3.970868,0.041265,0.113618,30.291695,F,Control
151675,3592,64999,1695,233478770,0.97,0.921,0.97,0.955,0.872,0.97,...,0.021,0.921,21344,3139,3.457127,0.064498,0.160123,30.291695,F,Control
151676,3460,92701,1813,320748023,0.972,0.938,0.97,0.951,0.965,0.97,...,0.017,0.93,21312,3419,3.242775,0.085106,0.186535,30.291695,F,Control

In [31]:
int_cols_bool = table_s1.columns.str.contains("number|median|total", regex=True)
string_cols_bool = table_s1.columns.isin({"sex", "primary_diagnosis"})

In [32]:
table_s1[table_s1.columns[int_cols_bool]] = table_s1[table_s1.columns[int_cols_bool]].astype(int) #.apply(lambda x: x.astype(int), axis=0)

In [33]:
float_cols_bool = ~(int_cols_bool | string_cols_bool)
table_s1[table_s1.columns[float_cols_bool]] = table_s1[table_s1.columns[float_cols_bool]].astype(float)

In [34]:
table_s1[table_s1.columns[string_cols_bool]] = table_s1[table_s1.columns[string_cols_bool]].astype("category")

In [35]:
table_s1.dtypes

SlideID
estimated_number_of_spots                            int64
mean_reads_per_spot                                float64
median_genes_per_spot                                int64
number_of_reads                                      int64
valid_barcodes                                     float64
sequencing_saturation                              float64
q30_bases_in_barcode                               float64
q30_bases_in_rna_read                              float64
q30_bases_in_sample_index                          float64
q30_bases_in_umi                                   float64
reads_mapped_to_genome                             float64
reads_mapped_confidently_to_genome                 float64
reads_mapped_confidently_to_intergenic_regions     float64
reads_mapped_confidently_to_intronic_regions       float64
reads_mapped_confidently_to_exonic_regions         float64
reads_mapped_confidently_to_transcriptome          float64
reads_mapped_antisense_to_gene                     float64
fraction_reads_in_spots                            float64
total_genes_detected                                 int64
median_umi_counts_per_spot                           int64
mean_cells_per_spot                                float64
proportion_0_cells_per_spot                        float64
proportion_1_cell_per_spot                         float64
age_death                                          float64
sex                                               category
primary_diagnosis                                 category
dtype: object

In [36]:
table_s1.columns = table_s1.columns.map(lambda x: "table_s1." + x)

In [37]:
adata.obs = adata.obs.merge(table_s1, how="left", left_on="sample_id", right_index=True, suffixes=("", ".table_s1"))

In [38]:
adata.obs.columns

Index(['sample_id', 'spot', 'X', 'Y', 'Cluster', 'sum_umi', 'sum_gene',
       'subject', 'position', 'replicate', 'subject_position', 'discard',
       'key', 'cell_count', 'SNN_k50_k4', 'SNN_k50_k5', 'SNN_k50_k6',
       'SNN_k50_k7', 'SNN_k50_k8', 'SNN_k50_k9', 'SNN_k50_k10', 'SNN_k50_k11',
       'SNN_k50_k12', 'SNN_k50_k13', 'SNN_k50_k14', 'SNN_k50_k15',
       'SNN_k50_k16', 'SNN_k50_k17', 'SNN_k50_k18', 'SNN_k50_k19',
       'SNN_k50_k20', 'SNN_k50_k21', 'SNN_k50_k22', 'SNN_k50_k23',
       'SNN_k50_k24', 'SNN_k50_k25', 'SNN_k50_k26', 'SNN_k50_k27',
       'SNN_k50_k28', 'GraphBased', 'Maynard', 'Martinowich', 'layer_guess',
       'layer_guess_reordered', 'layer_guess_reordered_short', 'expr_chrM',
       'expr_chrM_ratio', 'SpatialDE_PCA', 'SpatialDE_pool_PCA', 'HVG_PCA',
       'pseudobulk_PCA', 'markers_PCA', 'SpatialDE_UMAP',
       'SpatialDE_pool_UMAP', 'HVG_UMAP', 'pseudobulk_UMAP', 'markers_UMAP',
       'SpatialDE_PCA_spatial', 'SpatialDE_pool_PCA_spatial',
       'HVG_PCA_spatial', 'pseudobulk_PCA_spatial', 'markers_PCA_spatial',
       'SpatialDE_UMAP_spatial', 'SpatialDE_pool_UMAP_spatial',
       'HVG_UMAP_spatial', 'pseudobulk_UMAP_spatial', 'markers_UMAP_spatial',
       'spatialLIBD', 'ManualAnnotation', 'in_tissue', 'array_row',
       'array_col', 'table_s1.estimated_number_of_spots',
       'table_s1.mean_reads_per_spot', 'table_s1.median_genes_per_spot',
       'table_s1.number_of_reads', 'table_s1.valid_barcodes',
       'table_s1.sequencing_saturation', 'table_s1.q30_bases_in_barcode',
       'table_s1.q30_bases_in_rna_read', 'table_s1.q30_bases_in_sample_index',
       'table_s1.q30_bases_in_umi', 'table_s1.reads_mapped_to_genome',
       'table_s1.reads_mapped_confidently_to_genome',
       'table_s1.reads_mapped_confidently_to_intergenic_regions',
       'table_s1.reads_mapped_confidently_to_intronic_regions',
       'table_s1.reads_mapped_confidently_to_exonic_regions',
       'table_s1.reads_mapped_confidently_to_transcriptome',
       'table_s1.reads_mapped_antisense_to_gene',
       'table_s1.fraction_reads_in_spots', 'table_s1.total_genes_detected',
       'table_s1.median_umi_counts_per_spot', 'table_s1.mean_cells_per_spot',
       'table_s1.proportion_0_cells_per_spot',
       'table_s1.proportion_1_cell_per_spot', 'table_s1.age_death',
       'table_s1.sex', 'table_s1.primary_diagnosis'],
      dtype='object')

In [39]:
adata.write_h5ad(os.path.join(OUT_DIR, "spatialLIBD.h5ad"))